### ISSUE TITLE
Error spam

### ISSUE THREAD

**Issue by Boy0000** [MineInAbyss/geary#75]
This is currently spamming console but i can find no entry for kuongatari_abdomen in the config, just with _raw and _cooked as intended

Increases the logfile size with about 10mb per minute
![image](https://user-images.githubusercontent.com/62521371/184532239-3e9b29c0-42c1-4839-8b76-a15889ad0c7c.png)

```
[11:40:07] [Server thread/ERROR]: [Geary] Error while running system ItemTrackerSystem
[11:40:07] [Server thread/WARN]: java.lang.IllegalStateException: Requested non null prefab entity for mineinabyss:kuongatari_abdomen, but it does not exist.
[11:40:07] [Server thread/WARN]: 	at geary-papermc-0.18.106-all.jar//com.mineinabyss.geary.prefabs.PrefabKey.toEntity-lvC7dM0(PrefabKey.kt:20)
[11:40:07] [Server thread/WARN]: 	at looty-0.7.58.jar//com.mineinabyss.looty.LootyFactory.getItemState(LootyFactory.kt:80)
[11:40:07] [Server thread/WARN]: 	at looty-0.7.58.jar//com.mineinabyss.looty.ecs.systems.tracking.ItemTrackerSystem$Companion.refresh$calculateForItem(ItemTrackerSystem.kt:118)
[11:40:07] [Server thread/WARN]: 	at looty-0.7.58.jar//com.mineinabyss.looty.ecs.systems.tracking.ItemTrackerSystem$Companion.refresh(ItemTrackerSystem.kt:136)
[11:40:07] [Server thread/WARN]: 	at looty-0.7.58.jar//com.mineinabyss.looty.ecs.systems.tracking.ItemTrackerSystem.tick(ItemTrackerSystem.kt:46)
[11:40:07] [Server thread/WARN]: 	at geary-papermc-0.18.106-all.jar//com.mineinabyss.geary.systems.TickingSystem.tick(TickingSystem.kt:33)
[11:40:07] [Server thread/WARN]: 	at geary-papermc-0.18.106-all.jar//com.mineinabyss.geary.systems.TickingSystem.doTick(TickingSystem.kt:29)
[11:40:07] [Server thread/WARN]: 	at geary-papermc-0.18.106-all.jar//com.mineinabyss.geary.papermc.engine.PaperMCEngine.runSystem(PaperMCEngine.kt:24)
[11:40:07] [Server thread/WARN]: 	at geary-papermc-0.18.106-all.jar//com.mineinabyss.geary.engine.GearyEngine$tick$2$job$1.invokeSuspend(GearyEngine.kt:296)
[11:40:07] [Server thread/WARN]: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
[11:40:07] [Server thread/WARN]: 	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:367)
[11:40:07] [Server thread/WARN]: 	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith$default(DispatchedContinuation.kt:278)
[11:40:07] [Server thread/WARN]: 	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:39)
[11:40:07] [Server thread/WARN]: 	at kotlinx.coroutines.LazyStandaloneCoroutine.onStart(Builders.common.kt:205)
[11:40:07] [Server thread/WARN]: 	at kotlinx.coroutines.JobSupport.startInternal(JobSupport.kt:396)
[11:40:07] [Server thread/WARN]: 	at kotlinx.coroutines.JobSupport.start(JobSupport.kt:380)
[11:40:07] [Server thread/WARN]: 	at geary-papermc-0.18.106-all.jar//com.mineinabyss.geary.engine.GearyEngine$tick$2.invokeSuspend(GearyEngine.kt:311)
[11:40:07] [Server thread/WARN]: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
[11:40:07] [Server thread/WARN]: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
[11:40:07] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
[11:40:07] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[11:40:07] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1490)
[11:40:07] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:446)
[11:40:07] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1414)
[11:40:07] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1187)
[11:40:07] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302)
[11:40:07] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by Boy0000** [comment]
From looking into what throws the error, the msg is only linked to `/geary reread` so ill assume that someone reread it.
Why it tried to reread a prefab that doesnt exist idk
